### ISSUE TITLE
Conditions werden nicht heruntergeladen

### ISSUE THREAD

**Issue by stolzA** [medizininformatik-initiative/Projectathon7-VHF-DataExtraction#7]
```Extracting data for cond...
Traceback (most recent call last):
  File "/opt/data-extraction/data-selection-and-extraction.py", line 167, in <module>
    extracted_res_list = extracted_res_list + get_all_res_for_query(temp_query, False)
  File "/opt/data-extraction/data-selection-and-extraction.py", line 121, in get_all_res_for_query
    return page_through_results_and_collect(resp_json, resources)
  File "/opt/data-extraction/data-selection-and-extraction.py", line 112, in page_through_results_and_collect
    list(map(lambda entry: entry['resource'], resp.json()['entry']))
KeyError: 'entry'```

**Comment by stolzA** [comment]
Ich habe den Fehler selbst gefunden. Eine Errorhandling und entsprechendes Logging in dem Skript wären ganz toll!
